### ISSUE TITLE
error: OpenCV(4.5.5) /io/opencv/modules/dnn/src/layers/convolution_layer.cpp:404: error: (-2:Unspecified error) Number of input channels should be multiple of 3 but got 4 in function 'getMemoryShapes'

### ISSUE THREAD

**Issue by tobimichigan** [by256/imagedataextractor#13]
Hi there, nice work.
However, please it how can we implement new case image besides the examples given in your Jupyter Notebook?
Cos the last time i TRIED, IT GAVE THIS ERROR:
error: OpenCV(4.5.5) /io/opencv/modules/dnn/src/layers/convolution_layer.cpp:404: error: (-2:Unspecified error) Number of input channels should be multiple of 3 but got 4 in function 'getMemoryShapes'
![image](https://user-images.githubusercontent.com/5084987/168701916-00e92e1e-4ccf-4807-8e9a-3432ce715008.png)

Kindly suggest an appropriate solution. Thank you.

**Comment by by256** [comment]
Hi Tobi. It looks like you're using a 4-channel RGBA image as input. The easiest thing to try would be to edit the image (either with a Python script or some image processing software) to remove the 4th channel and convert it to RGB.

There should really be functionality to check for this and convert 4-channel inputs to 3-channel when necessary in imagedataextractor, but I don't have time at the moment to implement it.
