### ISSUE TITLE
Not reading image files

### ISSUE THREAD

**Issue by vinven7** [by256/imagedataextractor#9]
`import imagedataextractor as ide
input_path='ide1.jpg'
dat = ide.extract(input_path)`

`error                                     Traceback (most recent call last)
<ipython-input-3-9c86cd787502> in <module>
      1 input_path='ide1.jpg'
----> 2 dat = ide.extract(input_path)

~/anaconda3/envs/vineeth/lib/python3.6/site-packages/imagedataextractor/extract.py in extract(input_path, seg_bayesian, seg_n_samples, seg_tu, seg_device)
     61                 images = [image]
     62             for i, im in enumerate(images):
---> 63                 em_data = _extract_image(im, seg_bayesian, seg_n_samples, seg_tu, seg_device)
     64                 if len(images) == 1:
     65                     em_data.fn = fn

~/anaconda3/envs/vineeth/lib/python3.6/site-packages/imagedataextractor/extract.py in _extract_image(image, seg_bayesian, seg_n_samples, seg_tu, seg_device)
    139 
    140     # detect scalebar
--> 141     scalebar = sb_detector.detect(image)
    142     em_data.scalebar = scalebar
    143     text, units, conversion, scalebar_contour = scalebar.data

~/anaconda3/envs/vineeth/lib/python3.6/site-packages/imagedataextractor/scalebar/scalebar.py in detect(self, image)
    108         scalebar = Scalebar()
    109 
--> 110         rois, roi_locs = self.text_detector.get_text_rois(image)
    111         text, best_idx = self.ocr.get_text_from_rois(rois)
    112 

~/anaconda3/envs/vineeth/lib/python3.6/site-packages/imagedataextractor/scalebar/textdetection.py in get_text_rois(self, image, scale, augment)
     96         rois = []
     97         roi_locs = []
---> 98         boxes = self.detect_text(image)
     99         for x1, y1, x2, y2 in boxes:
    100             box_w = int(scale * (x2 - x1))

~/anaconda3/envs/vineeth/lib/python3.6/site-packages/imagedataextractor/scalebar/textdetection.py in detect_text(self, image)
     89         blob = cv2.dnn.blobFromImage(image, **blob_params)
     90         self.model.setInput(blob)
---> 91         scores, geometry = self.model.forward(self.layer_names)
     92         boxes = self.postprocess_detections(scores, geometry)
     93         return boxes

error: OpenCV(4.5.3) /tmp/pip-req-build-tjxnaiom/opencv/modules/dnn/src/layers/convolution_layer.cpp:385: error: (-2:Unspecified error) Number of input channels should be multiple of 3 but got 1 in function 'getMemoryShapes'`

**Comment by vinven7** [comment]
The actual image shape is (290,372,3)

**Comment by by256** [comment]
Hmm that's strange. The first thing that comes to mind is that it could be that the version of opencv you are using is incompatible. Could you confirm that you are using these version of the following libraries:

opencv-python: 4.2.0.32
pytesseract: 0.3.3

@vinven7

**Comment by by256** [comment]
@vinven7 any luck?
